// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR1MOo6BJ3XsTb2B5wNqEuEz9n-Ewo4B4',
    appId: '1:780477059466:web:f1d5c2775460cf4f7c7873',
    messagingSenderId: '780477059466',
    projectId: 'uygulamam-20bf3',
    authDomain: 'uygulamam-20bf3.firebaseapp.com',
    storageBucket: 'uygulamam-20bf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUWiUV2HM5COrPLCVzpQEWYP9Bdhmq890',
    appId: '1:780477059466:android:9cc79f3ee5fd833f7c7873',
    messagingSenderId: '780477059466',
    projectId: 'uygulamam-20bf3',
    storageBucket: 'uygulamam-20bf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeEy96sGnxAt8Qp4vBib0VeuzcOimX3J4',
    appId: '1:780477059466:ios:ecc42883b6a449ea7c7873',
    messagingSenderId: '780477059466',
    projectId: 'uygulamam-20bf3',
    storageBucket: 'uygulamam-20bf3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeEy96sGnxAt8Qp4vBib0VeuzcOimX3J4',
    appId: '1:780477059466:ios:ecc42883b6a449ea7c7873',
    messagingSenderId: '780477059466',
    projectId: 'uygulamam-20bf3',
    storageBucket: 'uygulamam-20bf3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
